### ISSUE TITLE
[Bug] Application hangs after pressing "Run checkm8" on macOS Big Sur 11.3 beta

### ISSUE THREAD

**Issue by PoomSmart** [MatthewPierson/Ramiel#1]
**Describe the bug**

It is known that macOS Big Sur 11.3 beta breaks checkm8 exploit over USB, for some reasons. For my case, `eclipsa8000` binary will never terminate, causing the whole application to hang - just like when running directly from `ipwndfu`.

The application should at least display an error that the exploit failed to work.

Reference: https://www.reddit.com/r/jailbreak/comments/ldbhfv/news_macos_big_sur_11_beta_3_intel_breaks/

**To Reproduce**

**Expected behavior**

**Screenshots**

<img width="644" alt="image" src="https://user-images.githubusercontent.com/3608783/111065516-c3611580-84ec-11eb-8ea4-30056535bfdb.png">

**Desktop (please complete the following information):**
 - macOS Version: 11.3 beta (20E5196f)
 - Machine Model: MacBook Pro 16"

**iOS/iPadOS Device(please complete the following information):**
 - Model: iPhone8,4
 - iOS Version Being Booted: iOS 13.5
 - Dualbooted: Y

**Additional context**

Not sure if this information would help. Console app is being spammed with this from Ramiel:
`... Ramiel@(null): AppleUSBHostUserClient::start: missing entitlement com.apple.ibridge.control`

**Comment by skyline9394** [comment]
you are not in pwndfu mode you need enter dfu and then download ipwndfu cd it and enter ./ipwndfu -p

**Comment by Guines10** [comment]
After ./ipwndfu -p, ERROR: This device is not supported
My device: iphone 8.1 (6s)

> you are not in pwndfu mode you need enter dfu and then download ipwndfu cd it and enter ./ipwndfu -p after that you can run ramiel

**Comment by skyline9394** [comment]
this error you need wait matty  make it support you device

**Comment by MatthewPierson** [comment]
@PoomSmart v1.0.2 adds in a timeout check for when exploiting the device takes over 30 seconds (30 seconds is a long time but to allow for slow A7 exploitation it needs to be around this long). If the timer hits 30 seconds it'll terminate the task and show an alert informing the user that the exploit timed out. I think this is a good way of dealing with the issue until a proper fix is found for the 11.3 Beta issues. The reason it wasn't displaying an error (when it should have been) was because my code was waiting for the program to return before it checked if it failed or not. This will fix that issue :) Thanks for letting me know about it!

**Comment by hsbugs** [comment]
it doesn's work on m1 devices  ERROR: Failed to exploit device, reason: TIMEOUT  help!
