### ISSUE TITLE
[Bug] Error while getting firmware keys.

### ISSUE THREAD

**Issue by alexander079** [MatthewPierson/Ramiel#16]
**Describe the bug**
Expected string lengths of 64 & 32 but got 7, 7 & 7, 7 -> Cannot dualboot

**To Reproduce**
1. Go to 'Ramiel'
2. After selecting IPSW, it began to unzip then verify.
3. See error

**Expected behavior**
Nothing happens except the error pops up.

**Screenshots**
https://imgur.com/GuF3aSN

**Desktop (please complete the following information):**
 - macOS Version: [11.2.2]
 - Machine Model: [Macbook Air 2017]

**iOS/iPadOS Device(please complete the following information):**
 - Model: [iPhone8,2]
 - iOS Version Being Booted: [iOS 13.5]
 - Dualbooted: [Y]

**Additional context**
None.

**Comment by alexander079** [comment]
Everything has been completed on my phone before opening Ramiel (to boot the second OS). 
One question is that is it okay to dualboot with 14 as main and 13.5 as second OS? 
Thanks in advance.

**Comment by MatthewPierson** [comment]
This is happening because there are no keys for your device (n66map). If you look at the attached image you will see what is on theiphonewiki. You will either need to find someone to get the keys and upload them to theiphonewiki for you, or do it yourself.
![image](https://user-images.githubusercontent.com/48230305/111439965-bfdac200-876a-11eb-9f0a-ec174c9d9663.png)

**Comment by alexander079** [comment]
Okay thanks a lot.
